### ISSUE TITLE
Implementing C++ Consensus and Group functionalities in Python? 

### ISSUE THREAD

**Issue by mbellabah** [RIAPS/riaps-pycom#139]
Thanks for the great work RIAPS team!

I was wondering whether there are any plans to implement some of the consensus and group functionalities written in C++ into Python. If not, advice on how to integrate the riaps-core repo with my primarily Python project would be much appreciated.

**Comment by gkarsai** [comment]
Yes there are plans, but not in the immediate future (3 months horizon). 
The riaps-core packages can be used to develop pure C++ components (that can communicate with Python components).  The directories under riaps-apps/apps-vu/DistributedEstimator/  give examples. 
Note: you  want to use the DSML tools (including the code generator) to produce the skeleton code for the C++ components. Once compiled into dynamic link libraries they are loaded into the Python framework and run just like any Python component.
