### ISSUE TITLE
Seamless integration of spdlog with Python

### ISSUE THREAD

**Issue by volgy** [RIAPS/riaps-pycom#150]
Since we changed over the spdlog (from the standard Python logging), text format strings require to be evaluated before colling the log functions (i.e. `%` operator).
Indeed, we already started to *port* existing code to fix this *problem*. However, this is a bad idea, because:
 - The original late evaluation is more effective (if the log is not printed, it won't be interpolated)
 - If we ever use Python libraries which use standard Python logging, they fail

I suggest to add a proper shim for spdlog, which emulates the exact same API as Python logging.

**Comment by MMetelko** [comment]
It has been determined that adding a shim for this would require suggested changes to the spdlog library, this is more effort than is currently available.  Currently do not plan to implement this.
