### ISSUE TITLE
dc.send() assert error

### ISSUE THREAD

**Issue by imadari** [RIAPS/riaps-pycom#179]
In [this line](https://github.com/RIAPS/riaps-pycom/blob/e42dd5b1af1ffe139234daa4775eda1350ac27d6/src/riaps/run/dc.py#L899), this assert:

```py
assert(type(msg) == bytearray)
```

Should be:

```python
assert(type(msg) == bytes)
```

Looks like the serialized capnp message is 'bytes' in Python.

**Comment by gkarsai** [comment]
Good catch - thanks. Updated branch (code and docstrings).
