### ISSUE TITLE
Cannot disable leader in riaps file

### ISSUE THREAD

**Issue by imadari** [RIAPS/riaps-pycom#180]
The code assumes that the leader can be disabled, however the RIAPS language doesn't allow that.

In [relevant code](https://github.com/RIAPS/riaps-pycom/blob/e9297f0296b9d229daf4b12f98bd1e58834e6b27/src/riaps/run/dc.py#L835) the `else` part never runs, because `self.coordinated` cannot be `False`. `self.coordinated` is assigned [here](https://github.com/RIAPS/riaps-pycom/blob/e9297f0296b9d229daf4b12f98bd1e58834e6b27/src/riaps/run/dc.py#L785).

[Related part](https://github.com/RIAPS/riaps-pycom/blob/e9297f0296b9d229daf4b12f98bd1e58834e6b27/src/riaps/lang/riaps.tx#L32) in the RIAPS language.

**Comment by gkarsai** [comment]
The syntax for groups is:
Group:
  'group' name=ID (kind=GroupKind)?
  		  'using' message=[Message] (timed='timed')? ';' 
;
 
 GroupKind:
   'with' (kind='leader' | kind='consensus')
 ;
If the 'kind' clause is missing, it is 'default', i.e. no leader election/etc. 
See small fix in riaps/run/dc.py: do not throw exception if an uncoordinated group is used.
