### ISSUE TITLE
RIAPS registry with TCP doesnt  work

### ISSUE THREAD

**Issue by shekharshank** [RIAPS/riaps-pycom#194]
I get the following error with -m TCP option for rpyc_registry.py

Traceback (most recent call last):
  File "/usr/local/bin/rpyc_registry.py", line 42, in <module>
    RegistryServer.run()
  File "/usr/local/lib/python3.6/dist-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/bin/rpyc_registry.py", line 38, in main
    server.start()
UnboundLocalError: local variable 'server' referenced before assignment

Fix would be to change line 15 (at least for RIAPS 1.1.17) to 
```
mode = cli.SwitchAttr(["-m", "--mode"], cli.Set("UDP", "TCP", case_sensitive = True), default = "UDP",
        help = "Serving mode")
```

**Comment by shekharshank** [comment]
Also, is there any documentation available to switch from UDP to TCP for discovery? I am having issues when I scale the BBB cluster

**Comment by MMetelko** [comment]
RIAPS uses the `rpyc` python library.  The package installed is located at https://github.com/tomerfiliba-org/rpyc/tree/master.  Closing since this is a third party package.
