### ISSUE TITLE
msg is not defined

### ISSUE THREAD

**Issue by eiselesr** [RIAPS/riaps-pycom#201]
https://github.com/RIAPS/riaps-pycom/blob/8f9b79b12d4622619ae6b4becac73ae43fa47585/src/riaps/run/actor.py#L522

**Comment by MMetelko** [comment]
This looks to no longer be relevant given changes being applied for release 1.1.20.  Scott, please verify that you agree.

**Comment by eiselesr** [comment]
Yes, we can close this.
